openapi: "3.0.3"
info:
  title: "LPS follow-up plan API"
  description: "Maskinporten API for submitting follow-up plans to NAV and/or the employees general practitioner."
  version: "1.0.0"
paths:
  /api/test/token:
    get:
      description: "Fetching maskinporten-token for test environment"
      tags:
        - Token for testmiljø
      security:
        - basicAuth: [ ]
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
  /api/v1/followupplan/write:
    post:
      description: "Submit follow-up plan to NAV and/or general practitioner"
      tags:
        - Followup-plan API
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/FollowUpPlanDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/FollowUpPlanResponse"
  /api/v1/followupplan/read/sendingStatus/{uuid}:
    get:
      description: "Get a sending status to NAV and general practitioner by follow up plan id"
      tags:
        - Followup-plan API
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/FollowUpPlanResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token from maskinporten
    basicAuth:
      type: http
      scheme: basic
      description: "Kun til bruk for test-token"

  schemas:
    FollowUpPlanDTO:
      type: "object"
      properties:
        employeeIdentificationNumber:
          type: "string"
          description: "A Norwegian national identity number or D number."
        typicalWorkday:
          type: "string"
          description: "Description of a typical day at work."
        tasksThatCanStillBeDone:
          type: "string"
          description: "Ordinary tasks that still can be done."
        tasksThatCanNotBeDone:
          type: "string"
          description: "Ordinary tasks that can no longer be done because of illness."
        previousFacilitation:
          type: "string"
          description: "Any previous facilitation that has been done related to the employee's current illness."
        plannedFacilitation:
          type: "string"
          description: "Description of facilitation that will be done from now on."
        otherFacilitationOptions:
          type: "string"
          description: "Are there any other options for facilitation at the workplace that have not been tried out yet?"
        followUp:
          type: "string"
          description: "How will the employer/leader follow up the planned facilitation?"
        evaluationDate:
          type: "string"
          format: "date"
          description: "When will the employer/leader and employee evaluate this oppfolgingsplan?"
        sendPlanToNav:
          type: "boolean"
          description: "Do you want to send this plan to NAV?"
        needsHelpFromNav:
          type: "boolean"
          description: "Do you need help from NAV? If yes, a task will be created at NAVs internal systems. Only relevant if the plan should be sent to NAV."
        needsHelpFromNavDescription:
          type: "string"
          description: "Description of what kind of help is needed. Obligatory if needsHelpFromNav is true."
        sendPlanToGeneralPractitioner:
          type: "boolean"
          description: "Do you want to send this plan to the employee's general practitioner?"
        messageToGeneralPractitioner:
          type: "string"
          description: "Message to the general practitioner."
        additionalInformation:
          type: "string"
          description: "Additional information, if relevant."
        contactPersonFullName:
          type: "string"
          description: "Full name of the person responsible for following up the employee. Typically the nearest leader."
        contactPersonPhoneNumber:
          type: "string"
          description: "Phone number of the person responsible for following up the employee."
        contactPersonEmail:
          type: "string"
          description: "E-mail of the person responsible for following up the employee."
        employeeHasContributedToPlan:
          type: "boolean"
          description: "Has the employee been involved in the process of creating this plan?"
        employeeHasNotContributedToPlanDescription:
          type: "string"
          description: "Description of why the employee does not have contributed to the plan. Obligatory if employeeHasContributedToPlan is false."
        lpsName:
          type: "string"
          description: "Name of the consumer system sending in this plan"
      required:
      - "employeeIdentificationNumber"
      - "typicalWorkday"
      - "tasksThatCanStillBeDone"
      - "tasksThatCanNotBeDone"
      - "previousFacilitation"
      - "plannedFacilitation"
      - "followUp"
      - "evaluationDate"
      - "sendPlanToNav"
      - "sendPlanToGeneralPractitioner"
      - "contactPersonFullName"
      - "contactPersonPhoneNumber"
      - "contactPersonEmail"
      - "employeeHasContributedToPlan"

    FollowUpPlanResponse:
      type: "object"
      properties:
        uuid:
          type: "string"
          description: "An id for a follow up plan"
        isSentToGeneralPractitionerStatus:
          type: "string"
          description: "Status for sending a plan to general practitioner, true or false"
        isSentToNavStatus:
          type: "string"
          description: "Status for sending a plan to NAV, true or false"
