openapi: "3.0.3"
info:
  title: "LPS follow-up plan API"
  description: "Maskinporten API for submitting follow-up plans to NAV and/or the employees general practitioner."
  version: "1.0.0"
paths:
  /api/test/token:
    get:
      description: "Fetching maskinporten-token for test environment"
      tags:
        - Token for testmiljø
      security:
        - basicAuth: [ ]
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
  /api/v1/followupplan:
    post:
      description: "Submit follow-up plan to NAV and/or general practitioner"
      tags:
        - Followup-plan API
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/FollowUpPlanDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/FollowUpPlanResponse"
        "400":
          description: "Bad Request"
          content:
            'text/plain':
              schema:
                type: "string"
                example: "Invalid request. Error message: <Some error message>, Error cause: <Some cause>"
        "500":
          description: "Internal Server Error"
          content:
            'text/plain':
              schema:
                type: "string"
                example: "Failed to retrieve follow-up plan: <Some error message>"
  /api/v1/followupplan/{uuid}/sendingstatus:
    get:
      description: "Gets the sending status to NAV and general practitioner by follow up plan id"
      tags:
        - Followup-plan API
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/FollowUpPlanResponse"
        "400":
          description: "Bad Request"
          content:
            'text/plain':
              schema:
                type: "string"
                example: "Invalid request. Error message: <Some error message>, Error cause: <Some cause>"
        "404":
          description: "NotFound"
          content:
            'text/plain':
              schema:
                type: "string"
                example: "The follow-up plan with a given uuid not found"
        "500":
          description: "Internal Server Error"
          content:
            'text/plain':
              schema:
                type: "string"
                example: "Failed to retrieve follow-up plan: <Some error message>"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token from maskinporten
    basicAuth:
      type: http
      scheme: basic
      description: "Kun til bruk for test-token"

  schemas:
    FollowUpPlanDTO:
      type: "object"
      properties:
        employeeIdentificationNumber:
          type: "string"
          description: "A Norwegian national identity number or D number."
          example: "12345678901"
        typicalWorkday:
          type: "string"
          description: "Description of a typical day at work."
          example: "Leading the Galactic Empire, attending strategic meetings, lightsaber training"
        tasksThatCanStillBeDone:
          type: "string"
          description: "Ordinary tasks that still can be done."
          example: "Attending meetings, strategic planning"
        tasksThatCanNotBeDone:
          type: "string"
          description: "Ordinary tasks that can no longer be done because of illness."
          example: "Lightsaber training"
        previousFacilitation:
          type: "string"
          description: "Any previous facilitation that has been done related to the employee's current illness."
          example: "Provided ergonomic chair and voice amplifier"
        plannedFacilitation:
          type: "string"
          description: "Description of facilitation that will be done from now on."
          example: "Flexible working hours, remote command options"
        otherFacilitationOptions:
          type: "string"
          description: "Are there any other options for facilitation at the workplace that have not been tried out yet?"
          example: "Job rotation, task automation"
        followUp:
          type: "string"
          description: "How will the employer/leader follow up the planned facilitation?"
          example: "Weekly check-ins to discuss progress and adjustments"
        evaluationDate:
          type: "string"
          format: "date"
          description: "When will the employer/leader and employee evaluate this oppfolgingsplan?"
          example: "2023-12-31"
        sendPlanToNav:
          type: "boolean"
          description: "Do you want to send this plan to NAV?"
          example: true
        needsHelpFromNav:
          type: "boolean"
          description: "Do you need help from NAV? If yes, a task will be created at NAV's internal systems. 
          Only relevant if the plan should be sent to NAV, when sendPlanToNav is true. 
          Must be false when sendPlanToNav is false."
          example: true
        needsHelpFromNavDescription:
          type: "string"
          description: "Description of what kind of help is needed. 
          Obligatory if needsHelpFromNav is true. 
          Must be null if needsHelpFromNav is false."
          example: "Need assistance with job placement"
        sendPlanToGeneralPractitioner:
          type: "boolean"
          description: "Do you want to send this plan to the employee's general practitioner (fastlege)?"
          example: true
        messageToGeneralPractitioner:
          type: "string"
          description: "Message to the general practitioner (fastlege)."
          example: "Please review the follow-up plan for the patient"
        additionalInformation:
          type: "string"
          description: "Additional information, if relevant."
          example: "Darth Vader prefers to work in the evening due to health condition"
        contactPersonFullName:
          type: "string"
          description: "Full name of the person responsible for following up the employee. Typically the nearest leader."
          example: "Emperor Palpatine"
        contactPersonPhoneNumber:
          type: "string"
          description: "Phone number of the person responsible for following up the employee."
          example: "99999999"
        contactPersonEmail:
          type: "string"
          description: "E-mail of the person responsible for following up the employee."
          example: "emperor@empire.com"
        employeeHasContributedToPlan:
          type: "boolean"
          description: "Has the employee been involved in the process of creating this plan?"
          example: false
        employeeHasNotContributedToPlanDescription:
          type: "string"
          description: "Description of why the employee does not have contributed to the plan. 
          Obligatory if employeeHasContributedToPlan is false.
          Must be null if employeeHasContributedToPlan is true"
          example: "Employee was not available due to Sith business"
        lpsName:
          type: "string"
          description: "Name of the consumer system sending in this plan"
          example: "Empire HR System"
      required:
      - "employeeIdentificationNumber"
      - "typicalWorkday"
      - "tasksThatCanStillBeDone"
      - "tasksThatCanNotBeDone"
      - "previousFacilitation"
      - "plannedFacilitation"
      - "followUp"
      - "evaluationDate"
      - "sendPlanToNav"
      - "sendPlanToGeneralPractitioner"
      - "contactPersonFullName"
      - "contactPersonPhoneNumber"
      - "contactPersonEmail"
      - "employeeHasContributedToPlan"

    FollowUpPlanResponse:
      type: "object"
      properties:
        uuid:
          type: "string"
          description: "An id for a follow up plan"
        isSentToGeneralPractitionerStatus:
          type: "boolean"
          description: "Status for sending a plan to general practitioner, true or false"
        isSentToNavStatus:
          type: "boolean"
          description: "Status for sending a plan to NAV, true or false"
