apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: lps-oppfolgingsplan-mottak
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "v1.lps.write"
          enabled: true
          product: "oppfolgingsplan"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 30
          consumers:
            - name: "NAV"
              orgno: "889640782"
      consumes:
        - name: "nav:oppfolgingsplan:v1.lps.write"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  gcp:
    sqlInstances:
      - autoBackupHour: 1
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: GCP_DB
            name: lps-db
        diskAutoresize: true
        diskSize: 80
        diskType: SSD
        flags:
          - name: max_connections
            value: "50"
        highAvailability: true
        insights:
          enabled: true
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        name: lps-instance
        tier: db-custom-1-3840
        type: POSTGRES_15
  prometheus:
    enabled: true
    path: /prometheus
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: syfooppdfgen.intern.nav.no
        - host: dokarkiv.prod-fss-pub.nais.io
      rules:
        application: isdialogmelding
        namespace: teamsykefravr
  ingresses:
    - "https://lps-oppfolgingsplan-mottak.nav.no"
    - "https://lps-oppfolgingsplan-mottak.intern.nav.no"
  filesFrom:
    - secret: lps-oppfolgingsplan-mottak-secrets
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  leaderElection: true
  env:
    - name: KTOR_ENV
      value: remote
    - name: APPLICATION_PORT
      value: "8080"
    - name: COROUTINE_THREAD_POOL_SIZE
      value: "4"
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: OP_PDFGEN_URL
      value: http://syfooppdfgen
    - name: ISDIALOGMELDING_URL
      value: http://isdialogmelding.teamsykefravr
    - name: ISDIALOGMELDING_CLIENT_ID
      value: api://prod-gcp.teamsykefravr.isdialogmelding/.default
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: SEND_TO_FASTLEGE_RETRY_THRESHOLD
      value: "6"
